# Generated by Django 2.2.10 on 2020-06-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.AlterField(
            model_name='phone',
            name='dbid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
